//color scheme
export const lightGrey = [0xCFD6DA, '#CFD6DA'];
export const  teal = [0x80cbc4,'#80cbc4'];
export const  blue = [0x81B0F1,'#81B0F1'];
export const yellow =[0xE5B168,'#E5B168'];
export const green = [0x92CB86, '#92CB86'];
export const red=[0xF17077,'#F17077'];
export const blueGrey500 = [0x607d8b, '#607d8b'];
export const blueGrey600 = [0x546e7a, '#546e7a'];
export const grey = [0x666666, '#666666'];
export const name = { font: "90px lintelregular", fill: blueGrey600[1], boundsAlignH: "center", boundsAlignV: "middle" };
export const title = { font: "30px lintelregular", fill: green[1], boundsAlignH: "center", boundsAlignV: "middle" };
export const banner = { font: "20px lintelregular", fill: 'grey', boundsAlignH: "center", boundsAlignV: "middle" };
export const chart = { font: "25px Roboto", fill: blueGrey500[1], boundsAlignH: "center", boundsAlignV: "middle" };
export const h1 = { font: "30px Roboto", fill: 'white', boundsAlignH: "left", boundsAlignV: "middle" };
export const h2 = { font: "15px Roboto", fill: 'grey', boundsAlignH: "left", boundsAlignV: "middle" };
export const terminal = { font: "20px Roboto Mono", fill: red[1]};
export const card = { font: "120px Electrolize", fill: blueGrey600[1], boundsAlignH: "center", boundsAlignV: "middle" };
export const levels = { font: "20px Roboto", fill: 'white', boundsAlignH: "center", boundsAlignV: "middle" };
export const skills = { font: "25px Roboto", fill: 'white', boundsAlignH: "left", boundsAlignV: "middle" };
export const degreeTitle = {font: "45px lintelregular", fill: yellow[1], boundsAlignH: "left", boundsAlignV: "top"}
export const certifications = {font: "45px lintelregular", fill: blue[1], boundsAlignH: "left", boundsAlignV: "top"}
export const year = {font: "45px lintelregular", fill: blueGrey600[1], boundsAlignH: "right", boundsAlignV: "top"}
export const bullets = {font: "30px Roboto", fill: blueGrey600[1], boundsAlignH: "center", boundsAlignV: "middle"}
